/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import esper.Config;
import events.*;

import javax.swing.*;

/**
 * @author pitos
 */
public class ElectronicControlUnitView extends javax.swing.JFrame {
    
    /**
     * Creates new form ElectronicControlUnitView
     */
    public ElectronicControlUnitView() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCruiseOn = new javax.swing.JButton();
        jButtonCruiseOff = new javax.swing.JButton();
        jTextFieldSetSpeed = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCurrentSpeed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFuel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonTempIncrease = new javax.swing.JButton();
        jButtonTempDecrease = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCurrentTemp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldSetTemp = new javax.swing.JTextField();
        jToggleButtonHandbrake = new javax.swing.JToggleButton();
        jToggleButtonDecelerate = new javax.swing.JToggleButton();
        jToggleButtonAccelerate = new javax.swing.JToggleButton();
        jToggleButtonCruiseAccelerate = new javax.swing.JToggleButton();
        jToggleButtonCruiseDecelerate = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldRefuel = new javax.swing.JTextField();
        jButtonRefuel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCheckBoxOil = new javax.swing.JCheckBox();
        jCheckBoxAir = new javax.swing.JCheckBox();
        jCheckBoxMajor = new javax.swing.JCheckBox();
        jButtonOilComplete = new javax.swing.JButton();
        jButtonAirComplete = new javax.swing.JButton();
        jButtonMajorComplete = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldMileage = new javax.swing.JTextField();
        jButtonACStart = new javax.swing.JButton();
        jButtonACStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCruiseOn.setText("Cruise On");
        jButtonCruiseOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCruiseOnActionPerformed(evt);
            }
        });

        jButtonCruiseOff.setText("Cruise Off");
        jButtonCruiseOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCruiseOffActionPerformed(evt);
            }
        });

        jTextFieldSetSpeed.setText("0");

        jLabel1.setText("Set Speed");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Auto Mobile System");

        jLabel3.setText("Pedals");

        jTextFieldCurrentSpeed.setEditable(false);
        jTextFieldCurrentSpeed.setText("0");

        jLabel4.setText("Current Speed");

        jLabel5.setText("Fuel Sensor");

        jTextFieldFuel.setEditable(false);
        jTextFieldFuel.setText("0");

        jLabel7.setText("Air Conditioner");

        jButtonTempIncrease.setText("Increase Temp");
        jButtonTempIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTempIncreaseActionPerformed(evt);
            }
        });

        jButtonTempDecrease.setText("Decrease Temp");
        jButtonTempDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTempDecreaseActionPerformed(evt);
            }
        });

        jLabel8.setText("Current Temp");

        jTextFieldCurrentTemp.setEditable(false);

        jLabel9.setText("Set Temp");

        jTextFieldSetTemp.setEditable(false);

        jToggleButtonHandbrake.setText("Handbrake");
        jToggleButtonHandbrake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonHandbrakeActionPerformed(evt);
            }
        });

        jToggleButtonDecelerate.setText("Decelerate");
        jToggleButtonDecelerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonDecelerateActionPerformed(evt);
            }
        });

        jToggleButtonAccelerate.setText("Accelerate");
        jToggleButtonAccelerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAccelerateActionPerformed(evt);
            }
        });

        jToggleButtonCruiseAccelerate.setText("Accelerate");
        jToggleButtonCruiseAccelerate.setEnabled(false);
        jToggleButtonCruiseAccelerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCruiseAccelerateActionPerformed(evt);
            }
        });

        jToggleButtonCruiseDecelerate.setText("Decelerate");
        jToggleButtonCruiseDecelerate.setEnabled(false);
        jToggleButtonCruiseDecelerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCruiseDecelerateActionPerformed(evt);
            }
        });

        jLabel10.setText("Cruise Control");

        jLabel11.setText("Refuel");

        jTextFieldRefuel.setText("0");

        jButtonRefuel.setText("Submit");
        jButtonRefuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefuelActionPerformed(evt);
            }
        });

        jLabel12.setText("Maintenance");

        jLabel13.setText("Oil Filter");

        jLabel14.setText("Air Filter");

        jLabel15.setText("Major Service");

        jCheckBoxOil.setEnabled(false);

        jCheckBoxAir.setEnabled(false);

        jCheckBoxMajor.setEnabled(false);

        jButtonOilComplete.setText("Complete");
        jButtonOilComplete.setEnabled(false);
        jButtonOilComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOilCompleteActionPerformed(evt);
            }
        });

        jButtonAirComplete.setText("Complete");
        jButtonAirComplete.setEnabled(false);
        jButtonAirComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAirCompleteActionPerformed(evt);
            }
        });

        jButtonMajorComplete.setText("Complete");
        jButtonMajorComplete.setEnabled(false);
        jButtonMajorComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMajorCompleteActionPerformed(evt);
            }
        });

        jLabel16.setText("Mileage");

        jTextFieldMileage.setEditable(false);
        jTextFieldMileage.setText("0");

        jButtonACStart.setText("Start");
        jButtonACStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonACStartActionPerformed(evt);
            }
        });

        jButtonACStop.setText("Stop");
        jButtonACStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonACStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButtonCruiseAccelerate)
                    .addComponent(jButtonCruiseOn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButtonCruiseDecelerate)
                    .addComponent(jButtonCruiseOff))
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel2)
                .addGap(0, 245, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldSetSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButtonOilComplete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jButtonAirComplete))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jCheckBoxOil)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jCheckBoxAir)))
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jCheckBoxMajor))
                            .addComponent(jButtonMajorComplete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel16))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCurrentSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldRefuel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRefuel)))
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonACStart)
                        .addGap(52, 52, 52)
                        .addComponent(jButtonACStop)
                        .addGap(66, 66, 66))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonTempIncrease)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonTempDecrease))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(95, 95, 95))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldCurrentTemp)
                                .addComponent(jTextFieldSetTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(46, 46, 46)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jToggleButtonDecelerate)
                            .addGap(28, 28, 28)
                            .addComponent(jToggleButtonAccelerate)
                            .addGap(80, 80, 80))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jToggleButtonHandbrake, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(118, 118, 118)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldCurrentSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSetTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCurrentTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonTempIncrease)
                            .addComponent(jButtonTempDecrease))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonACStart)
                            .addComponent(jButtonACStop))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldRefuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRefuel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButtonDecelerate)
                            .addComponent(jToggleButtonAccelerate))
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonHandbrake)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxOil)
                            .addComponent(jCheckBoxAir)
                            .addComponent(jCheckBoxMajor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldSetSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(134, 134, 134))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonCruiseOn)
                                    .addComponent(jButtonCruiseOff, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jToggleButtonCruiseDecelerate)
                                    .addComponent(jToggleButtonCruiseAccelerate))
                                .addGap(51, 51, 51))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAirComplete)
                            .addComponent(jButtonMajorComplete)
                            .addComponent(jButtonOilComplete))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonACStartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonACStartActionPerformed
        Config.sendEvent(new ACButtonState(true));
    }// GEN-LAST:event_jButtonACStartActionPerformed
    
    private void jButtonACStopActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonACStopActionPerformed
        Config.sendEvent(new ACButtonState(false));
    }// GEN-LAST:event_jButtonACStopActionPerformed
    
    private void jButtonOilCompleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonOilCompleteActionPerformed
        Config.sendEvent(new MaintenanceCompletion(1));
    }// GEN-LAST:event_jButtonOilCompleteActionPerformed
    
    private void jButtonAirCompleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAirCompleteActionPerformed
        Config.sendEvent(new MaintenanceCompletion(2));
    }// GEN-LAST:event_jButtonAirCompleteActionPerformed
    
    private void jButtonMajorCompleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonMajorCompleteActionPerformed
        Config.sendEvent(new MaintenanceCompletion(3));
    }// GEN-LAST:event_jButtonMajorCompleteActionPerformed
    
    private void jButtonRefuelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRefuelActionPerformed
        if (jTextFieldRefuel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a fuel amount.");
            return;
        }
        
        double fuelAmount = Double.parseDouble(jTextFieldRefuel.getText());
        Config.sendEvent(new EnterFuelAmount(fuelAmount));
    }// GEN-LAST:event_jButtonRefuelActionPerformed
    
    private void jButtonCruiseOnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCruiseOnActionPerformed
        if (jToggleButtonHandbrake.isSelected()) {
            return;
        }
        if (jToggleButtonDecelerate.isSelected()) {
            jToggleButtonDecelerate.setSelected(false);
        }
        if (jToggleButtonAccelerate.isSelected()) {
            jToggleButtonAccelerate.setSelected(false);
        }
        
        if (jTextFieldSetSpeed.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the speed cruise control should be set to.");
            return;
        }
        if (jTextFieldSetSpeed.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Cruise control cannot be set to 0.");
            return;
        }
        
        jToggleButtonDecelerate.setEnabled(true);
        jToggleButtonAccelerate.setEnabled(true);
        
        double speed = Double.parseDouble(jTextFieldSetSpeed.getText());
        Config.sendEvent(new CruiseButtonState(true, speed));
    }// GEN-LAST:event_jButtonCruiseOnActionPerformed
    
    private void jButtonCruiseOffActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCruiseOffActionPerformed
        if (jToggleButtonHandbrake.isSelected()) {
            return;
        }
        jToggleButtonDecelerate.setEnabled(false);
        jToggleButtonAccelerate.setEnabled(false);
        
        jTextFieldSetSpeed.setText("0");
        Config.sendEvent(new CruiseButtonState(false, 0));
    }// GEN-LAST:event_jButtonCruiseOffActionPerformed
    
    private void jToggleButtonCruiseAccelerateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST
        if (jToggleButtonCruiseDecelerate.isSelected()) {
            jToggleButtonCruiseDecelerate.setSelected(false);
        }
        
        boolean toggleState = jToggleButtonCruiseAccelerate.isSelected();
        Config.sendEvent(new AccelerateButtonState(toggleState));
    }// GEN-LAST:event_jToggleButtonCruiseAccelerateActionPerformed
    
    private void jToggleButtonCruiseDecelerateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST
        if (jToggleButtonCruiseAccelerate.isSelected()) {
            jToggleButtonCruiseAccelerate.setSelected(false);
        }
        
        boolean toggleState = jToggleButtonCruiseDecelerate.isSelected();
        Config.sendEvent(new DecelerateButtonState(toggleState));
    }// GEN-LAST:event_jToggleButtonCruiseDecelerateActionPerformed
    
    private void jButtonTempIncreaseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonTempIncreaseActionPerformed
        Config.sendEvent(new ACTempButtons(true));
    }// GEN-LAST:event_jButtonTempIncreaseActionPerformed
    
    private void jButtonTempDecreaseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonTempDecreaseActionPerformed
        Config.sendEvent(new ACTempButtons(false));
    }// GEN-LAST:event_jButtonTempDecreaseActionPerformed
    
    private void jToggleButtonDecelerateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST
        if (jToggleButtonHandbrake.isSelected() || jToggleButtonAccelerate.isSelected()) {
            jToggleButtonDecelerate.setSelected(false);
            return;
        }
        
        boolean toggleState = jToggleButtonDecelerate.isSelected();
        Config.sendEvent(new DeceleratePedalState(toggleState));
    }// GEN-LAST:event_jToggleButtonDecelerateActionPerformed
    
    private void jToggleButtonAccelerateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST
        if (jToggleButtonHandbrake.isSelected() || jToggleButtonDecelerate.isSelected()) {
            jToggleButtonAccelerate.setSelected(false);
            return;
        }
        
        boolean toggleState = jToggleButtonAccelerate.isSelected();
        Config.sendEvent(new AcceleratePedalState(toggleState));
    }// GEN-LAST:event_jToggleButtonAccelerateActionPerformed
    
    private void jToggleButtonHandbrakeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST
        if (jToggleButtonAccelerate.isSelected()) {
            jToggleButtonAccelerate.setSelected(false);
        }
        if (jToggleButtonDecelerate.isSelected()) {
            jToggleButtonDecelerate.setSelected(false);
        }
        if (jToggleButtonCruiseAccelerate.isSelected()) {
            jToggleButtonCruiseAccelerate.setSelected(false);
        }
        if (jToggleButtonCruiseDecelerate.isSelected()) {
            jToggleButtonCruiseDecelerate.setSelected(false);
        }
        
        boolean toggleState = jToggleButtonHandbrake.isSelected();
        Config.sendEvent(new HandbrakeState(toggleState));
    }// GEN-LAST:event_jToggleButtonHandbrakeActionPerformed
    
    public JTextField getjTextFieldCurrentSpeed() {
        return jTextFieldCurrentSpeed;
    }
    
    public JTextField getjTextFieldCurrentTemp() {
        return jTextFieldCurrentTemp;
    }
    
    public JTextField getjTextFieldFuel() {
        return jTextFieldFuel;
    }
    
    public JTextField getjTextFieldSetSpeed() {
        return jTextFieldSetSpeed;
    }
    
    public JTextField getjTextFieldSetTemp() {
        return jTextFieldSetTemp;
    }
    
    public JTextField getjTextFieldMileage() {
        return jTextFieldMileage;
    }
    
    public JCheckBox getjCheckBoxOil() {
        return jCheckBoxOil;
    }
    
    public JCheckBox getjCheckBoxAir() {
        return jCheckBoxAir;
    }
    
    public JCheckBox getjCheckBoxMajor() {
        return jCheckBoxMajor;
    }
    
    public JButton getjButtonOilComplete() {
        return jButtonOilComplete;
    }
    
    public JButton getjButtonAirComplete() {
        return jButtonAirComplete;
    }
    
    public JButton getjButtonMajorComplete() {
        return jButtonMajorComplete;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElectronicControlUnitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElectronicControlUnitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElectronicControlUnitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElectronicControlUnitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElectronicControlUnitView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonACStart;
    private javax.swing.JButton jButtonACStop;
    private javax.swing.JButton jButtonAirComplete;
    private javax.swing.JButton jButtonCruiseOff;
    private javax.swing.JButton jButtonCruiseOn;
    private javax.swing.JButton jButtonMajorComplete;
    private javax.swing.JButton jButtonOilComplete;
    private javax.swing.JButton jButtonRefuel;
    private javax.swing.JButton jButtonTempDecrease;
    private javax.swing.JButton jButtonTempIncrease;
    private javax.swing.JCheckBox jCheckBoxAir;
    private javax.swing.JCheckBox jCheckBoxMajor;
    private javax.swing.JCheckBox jCheckBoxOil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldCurrentSpeed;
    private javax.swing.JTextField jTextFieldCurrentTemp;
    private javax.swing.JTextField jTextFieldFuel;
    private javax.swing.JTextField jTextFieldMileage;
    private javax.swing.JTextField jTextFieldRefuel;
    private javax.swing.JTextField jTextFieldSetSpeed;
    private javax.swing.JTextField jTextFieldSetTemp;
    private javax.swing.JToggleButton jToggleButtonAccelerate;
    private javax.swing.JToggleButton jToggleButtonCruiseAccelerate;
    private javax.swing.JToggleButton jToggleButtonCruiseDecelerate;
    private javax.swing.JToggleButton jToggleButtonDecelerate;
    private javax.swing.JToggleButton jToggleButtonHandbrake;
    // End of variables declaration//GEN-END:variables
}



